# Generated by Django 5.2.7 on 2025-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_barangay_user_city_user_province_user_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
