# Generated by Django 5.2.7 on 2025-11-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
