# Generated by Django 5.2.7 on 2025-12-01 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
