# Generated by Django 5.2.7 on 2025-12-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='project',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='app.project'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
