# Generated by Django 5.2.7 on 2025-12-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_user_supervisor_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_profile', to='app.user'),
        ),
    ]
