# Generated by Django 5.2.7 on 2025-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_supervisor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='password_hash',
            field=models.CharField(default='PASSWORD', max_length=255),
        ),
    ]
