# Generated by Django 5.2.7 on 2025-12-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_phase_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='phase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='order',
        ),
    ]
