# Generated by Django 5.2.7 on 2025-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_phase_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='phase_name',
            field=models.CharField(choices=[('PHASE 1 - Pre-Construction Phase', 'PHASE 1 - Pre-Construction Phase'), ('PHASE 2 - Design Phase', 'PHASE 2 - Design Phase'), ('PHASE 3 - Procurement Phase', 'PHASE 3 - Procurement Phase'), ('PHASE 4 - Construction Phase', 'PHASE 4 - Construction Phase'), ('PHASE 5 - Testing & Commissioning Phase', 'PHASE 5 - Testing & Commissioning Phase'), ('PHASE 6 - Turnover / Close-Out Phase', 'PHASE 6 - Turnover / Close-Out Phase'), ('PHASE 7 - Post-Construction / Operation Phase', 'PHASE 7 - Post-Construction / Operation Phase')], max_length=100),
        ),
    ]
