# Generated by Django 5.2.7 on 2025-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_phase_phase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='expected_due_date',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='start_date',
        ),
        migrations.AddField(
            model_name='phase',
            name='days_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
