# Generated by Django 5.2.7 on 2025-12-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_phase_expected_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
