# Generated by Django 5.2.7 on 2025-12-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_project_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='status',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='pagibig_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='payrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='philhealth_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Engineer', 'Engineer'), ('Architect', 'Architect'), ('Mason', 'Mason'), ('Painter', 'Painter')], default='Supervisor', max_length=50),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='sss_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
