# Generated by Django 5.2.7 on 2025-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_supervisor_status_supervisor_pagibig_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='role',
            field=models.CharField(default='Supervisor', max_length=50),
        ),
    ]
