# Generated by Django 5.2.7 on 2025-12-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_supervisor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(default='PASSWORD', max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('role', models.CharField(default='Supervisor', max_length=50)),
                ('sss_id', models.CharField(blank=True, max_length=20, null=True)),
                ('philhealth_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pagibig_id', models.CharField(blank=True, max_length=20, null=True)),
                ('payrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='app.project')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to='app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
