# Generated by Django 5.2.7 on 2025-12-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_workers_delete_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('fieldworker_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('role', models.CharField(default='Mason', max_length=50)),
                ('sss_id', models.CharField(blank=True, max_length=20, null=True)),
                ('philhealth_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pagibig_id', models.CharField(blank=True, max_length=20, null=True)),
                ('payrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_workers', to='app.project')),
            ],
        ),
    ]
