# Generated by Django 5.2.7 on 2025-12-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_fieldworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworker',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_workers', to='app.user'),
        ),
    ]
