# Generated by Django 5.2.7 on 2025-12-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_fieldworker_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskFieldWorker',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('field_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_assignments', to='app.fieldworker')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workers', to='app.subtask')),
            ],
            options={
                'ordering': ['assigned_at'],
                'unique_together': {('subtask', 'field_worker')},
            },
        ),
    ]
