# Generated by Django 5.2.7 on 2025-12-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_supervisors_delete_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor_id',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='app.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='app.supervisors'),
        ),
    ]
