# Generated by Django 5.2.7 on 2025-12-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_project_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisors',
            name='user_id',
        ),
    ]
