# Generated by Django 5.2.7 on 2025-12-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_supervisors_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('break_in_time', models.TimeField(blank=True, null=True)),
                ('break_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_site', 'On Site'), ('on_break', 'On Break'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.fieldworker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.project')),
            ],
            options={
                'ordering': ['-attendance_date'],
                'unique_together': {('field_worker', 'attendance_date')},
            },
        ),
    ]
