# Generated by Django 5.2.7 on 2025-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='progress_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
